# User API Routes
controllers:
    resource:
        path: ../src/User/Infrastructure/Http/Controller/
        namespace: App\User\Infrastructure\Http\Controller
    type: attribute

# Book API Routes
book_controllers:
    resource:
        path: ../src/Book/Infrastructure/Http/Controller/
        namespace: App\Book\Infrastructure\Http\Controller
    type: attribute
